### ISSUE TITLE
[ux] Create UI for the general navigation menu

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#188]
Design reference 
https://miro.com/app/board/o9J_lMAQQZk=/

### Tasks

- [ ] Need to create the light version from the design reference.
- [ ] Create design for narrow screen.
- [ ] Menu should remain close on page change if it was before.
- [ ] Menu should remain open on page change if it was open before
- [ ] Don't show a menu on the login page.
- [ ] Register menu groups for the test project in a good structure.

blocked by #189
