### ISSUE TITLE
[feature] Create register menu group functionality

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#189]
### Requirements

1. Possibility add menu groups( dropdown ), custom link, and a model link( example add or view link of a model) on their specified order. 
2. Possibility to add an icon to each menu item.
3. Possibility to add items to menu group on their specified order.

### Task List

- [x] User must be able to see only those model links for which they have permission to view or edit.
- [x] Register menu items at the specified position.
- [x] Write validations and write tests to test them.
- [x] Write tests to check items order correctly.
- [x] Show warning and encourage user to use ``register_menu_group`` when using ``register_menu_items``.

**Comment by nemesisdesign** [comment]
@niteshsinha17 these issues will be closed when the work is merged in master. For now please just move the issues to the done column in your project board.
