### ISSUE TITLE
[enhancement] Restyle filters

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#196]
### Design reference 
https://miro.com/app/board/o9J_lMAQQZk=/
This is an old ref.
New one:
https://www.figma.com/file/vCdBAfFQ3HNH9KWwdO4XgC/OpenWISP?node-id=0%3A1

### Tasks

- [x] Restyle filter and find a way to show filters on top instead of showing them in the lateral sidebars.
- [x] Create an apply filter button so that all filters are applied at once.
- [x] Create dropdown in filters so they don't occupy large space.
- [x] Create a slider for the filter
- [x] Write some basic tests to test the functionality ( if possible ).
