### ISSUE TITLE
[test] Selenium test for Filters

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-utils#200]
Write selenium tests to ensure proper working of modified filters.
### Tasks

- [x] Log in to the admin site and ensure filters are visible on the change list page.
- [x] Test the filter dropdown is working properly.
- [x] Test filters are applied when the ``filter`` button is clicked.
- [ ] Test ``show all`` button works perfectly when clicked. **Not Req:** Removed this feature. 
- [x] Test ``clear all`` button working.

blocked by https://github.com/openwisp/openwisp-utils/issues/196.

**Comment by atb00ker** [comment]
> Also, create a checklist to show what is being tested and what is left ( In the PR description )

Where? I don't see it.

**Comment by niteshsinha17** [comment]
> > Also, create a checklist to show what is being tested and what is left ( In the PR description )
> 
> Where? I don't see it.

Thanks, I have created it.
